name: anosha_portfolio
description: "Anosha Ali - Software Engineer Portfolio"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  # iOS-style icons
  cupertino_icons: ^1.0.8

  # Open GitHub, LinkedIn, email, CV and other links
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended Flutter lint rules
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/certificates/
    - assets/cv/
    - assets/images/
    - assets/achievements/